name: fieldresearch
description: "A survey app"

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  
  flutter_screenutil: ^5.0.1+2
  flutter_form_builder: ^9.2.1
  drag_and_drop_lists: ^0.3.3
  super_drag_and_drop: ^0.8.5
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5
  dartz: ^0.10.1
  user_repository:
    path: packages/user_repository
  research_repository:
    path: packages/research_repository
  app_mixins:
    path: packages/app_mixins
  app_client:
    path: packages/app_client
  app_ui:
    path: packages/app_ui
  flutter_native_splash: ^2.4.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^2.0.0



flutter:

 
  uses-material-design: true

 
  assets:
    - lib/assets/images/google.png
    - lib/assets/app/logo.png
    - lib/assets/app/logo_splash.png



  fonts:
    - family: Poppins
      fonts:
        - asset: lib/assets/fonts/Poppins-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

