name: app_client
description: "Dart package which manages the client."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  equatable: ^2.0.5
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^2.0.0



flutter:

  uses-material-design: true


