name: app_repositories
description: "Dart package that manages app repositories."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.4 <4.0.0'


dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  local_auth_android: ^1.0.38
  local_auth: ^2.2.0
  flutter_secure_storage: ^9.2.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^2.0.0



flutter:

  uses-material-design: true


